#!/usr/bin/env python3
"""
Generate src/data/mentors.ts from the canonical mentor registry in backend/mentors/*.json.

The backend JSON files are the single source of truth for persona data.
Frontend-only presentation fields (expertise taglines, chronological order,
portrait framing) live in this script. Run after editing any mentor JSON:

    python3 scripts/generate_mentor_data.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MENTORS_DIR = ROOT / "backend" / "mentors"
OUT_FILE = ROOT / "src" / "data" / "mentors.ts"

# Chronological walk through computing history — the homepage journey order.
ORDER = [
    "ada_lovelace",
    "alan_turing",
    "grace_hopper",
    "margaret_hamilton",
    "dennis_ritchie",
    "barbara_liskov",
    "guido_van_rossum",
    "linus_torvalds",
]

# Frontend-only taglines (not part of the persona registry).
EXPERTISE = {
    "ada_lovelace": "Algorithmic elegance & mathematical vision",
    "alan_turing": "Computational theory & logical precision",
    "grace_hopper": "Debugging, clarity & systematic thinking",
    "margaret_hamilton": "Reliability, safety & mission-critical systems",
    "dennis_ritchie": "Minimalism, portability & foundational design",
    "barbara_liskov": "Abstraction principles & software design",
    "guido_van_rossum": "Readability, elegance & Pythonic style",
    "linus_torvalds": "Performance, structure & practical solutions",
}

# Portrait framing hints (CSS object-position) for images that aren't
# pre-centered circular crops.
PORTRAIT_POSITION = {
    "ada_lovelace": "center 15%",
}


def ts_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    loaded = {}
    for path in MENTORS_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        loaded[data["mentor_id"]] = data

    missing = [m for m in ORDER if m not in loaded]
    if missing:
        raise SystemExit(f"Missing mentor JSONs: {missing}")

    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate_mentor_data.py — do not edit by hand.")
    lines.append("// Source of truth: backend/mentors/*.json. Regenerate with:")
    lines.append("//   python3 scripts/generate_mentor_data.py")
    lines.append("")
    lines.append("export interface MentorFeedbackSection {")
    lines.append("  id: string;")
    lines.append("  label: string;")
    lines.append("  icon: string;")
    lines.append("  prompt: string;")
    lines.append("}")
    lines.append("")
    lines.append("export interface Mentor {")
    lines.append("  id: string;")
    lines.append("  name: string;")
    lines.append("  era: string;")
    lines.append("  icon: string;")
    lines.append("  accentColor: string;")
    lines.append("  avatarUrl: string;")
    lines.append("  greeting: string;")
    lines.append("  signatureClosing: string;")
    lines.append("  tone: string;")
    lines.append("  expertise: string;")
    lines.append("  focusAreas: string[];")
    lines.append("  feedbackSections: MentorFeedbackSection[];")
    lines.append("  /** CSS object-position hint for portraits that are not pre-centered */")
    lines.append("  portraitPosition?: string;")
    lines.append("}")
    lines.append("")
    lines.append("export const MENTORS: Mentor[] = [")

    for mentor_id in ORDER:
        m = loaded[mentor_id]
        lines.append("  {")
        lines.append(f"    id: {ts_str(m['mentor_id'])},")
        lines.append(f"    name: {ts_str(m['name'])},")
        lines.append(f"    era: {ts_str(m['era'])},")
        lines.append(f"    icon: {ts_str(m['icon'])},")
        lines.append(f"    accentColor: {ts_str(m['accent_color'])},")
        lines.append(f"    avatarUrl: {ts_str(m['avatar_url'])},")
        lines.append(f"    greeting: {ts_str(m['signature_opening'])},")
        lines.append(f"    signatureClosing: {ts_str(m['signature_closing'])},")
        lines.append(f"    tone: {ts_str(m['tone'])},")
        lines.append(f"    expertise: {ts_str(EXPERTISE[mentor_id])},")
        lines.append("    focusAreas: [")
        for area in m["focus_areas"]:
            lines.append(f"      {ts_str(area)},")
        lines.append("    ],")
        lines.append("    feedbackSections: [")
        for s in m["feedback_schema"]["sections"]:
            lines.append("      {")
            lines.append(f"        id: {ts_str(s['id'])},")
            lines.append(f"        label: {ts_str(s['label'])},")
            lines.append(f"        icon: {ts_str(s['icon'])},")
            lines.append(f"        prompt: {ts_str(s.get('prompt', ''))},")
            lines.append("      },")
        lines.append("    ],")
        if mentor_id in PORTRAIT_POSITION:
            lines.append(f"    portraitPosition: {ts_str(PORTRAIT_POSITION[mentor_id])},")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    lines.append("export const MENTORS_BY_ID: Record<string, Mentor> = Object.fromEntries(")
    lines.append("  MENTORS.map((m) => [m.id, m]),")
    lines.append(");")
    lines.append("")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_FILE} ({len(ORDER)} mentors)")


if __name__ == "__main__":
    main()
