// AUTO-GENERATED by scripts/generate_mentor_data.py — do not edit by hand.
// Source of truth: backend/mentors/*.json. Regenerate with:
//   python3 scripts/generate_mentor_data.py

export interface MentorFeedbackSection {
  id: string;
  label: string;
  icon: string;
  prompt: string;
}

export interface Mentor {
  id: string;
  name: string;
  era: string;
  icon: string;
  accentColor: string;
  avatarUrl: string;
  greeting: string;
  signatureClosing: string;
  tone: string;
  expertise: string;
  focusAreas: string[];
  feedbackSections: MentorFeedbackSection[];
  /** CSS object-position hint for portraits that are not pre-centered */
  portraitPosition?: string;
}

export const MENTORS: Mentor[] = [
  {
    id: "ada_lovelace",
    name: "Ada Lovelace",
    era: "London, 1843",
    icon: "🔮",
    accentColor: "#c08585",
    avatarUrl: "/mentors/ada_lovelace.jpg",
    greeting: "The Analytical Engine weaves algebraic patterns, just as the Jacquard loom weaves flowers and leaves.",
    signatureClosing: "The Engine awaits your next instruction.",
    tone: "poetic_mathematical",
    expertise: "Algorithmic elegance & mathematical vision",
    focusAreas: [
      "mathematical_elegance",
      "recurrence_relations",
      "foresight",
      "algorithmic_patterns",
    ],
    feedbackSections: [
      {
        id: "reading",
        label: "Reading",
        icon: "📖",
        prompt: "What the Engine sees in your code — the pattern it weaves.",
      },
      {
        id: "harmonies",
        label: "Harmonies",
        icon: "✨",
        prompt: "Where the threads align beautifully — strengths in structure, clarity, mathematical insight.",
      },
      {
        id: "dissonances",
        label: "Dissonances",
        icon: "⚠️",
        prompt: "Where the pattern frays — redundancy, missed abstraction, lack of foresight.",
      },
      {
        id: "refactor",
        label: "The Refactored Score",
        icon: "🎼",
        prompt: "A rewritten passage showing how the pattern might be woven more elegantly.",
      },
      {
        id: "challenge",
        label: "Your Next Movement",
        icon: "🎯",
        prompt: "A concrete exercise to extend the composition.",
      },
    ],
    portraitPosition: "center 15%",
  },
  {
    id: "alan_turing",
    name: "Alan Turing",
    era: "Milton Keynes, 1941",
    icon: "🧠",
    accentColor: "#a3a380",
    avatarUrl: "/mentors/alan_turing.jpg",
    greeting: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    signatureClosing: "The machine awaits your next instruction.",
    tone: "philosophical_precise",
    expertise: "Computational theory & logical precision",
    focusAreas: [
      "computability",
      "halting",
      "abstraction",
      "theoretical_foundations",
    ],
    feedbackSections: [
      {
        id: "termination",
        label: "Termination Conditions",
        icon: "🔄",
        prompt: "Does this computation always halt? What guarantees exist?",
      },
      {
        id: "complexity",
        label: "Computational Complexity",
        icon: "⚙️",
        prompt: "Can we construct a more efficient machine? Time/space trade-offs.",
      },
      {
        id: "beauty",
        label: "Mathematical Beauty",
        icon: "🎨",
        prompt: "Does the code mirror the mathematical recurrence perfectly?",
      },
      {
        id: "alternative",
        label: "Alternative Perspective",
        icon: "🔍",
        prompt: "Could a simpler mechanism suffice? An iterative automaton perhaps?",
      },
    ],
  },
  {
    id: "grace_hopper",
    name: "Grace Hopper",
    era: "Harvard, 1947",
    icon: "💻",
    accentColor: "#7492ad",
    avatarUrl: "/mentors/grace_hopper.jpg",
    greeting: "It's easier to ask forgiveness than it is to get permission.",
    signatureClosing: "Now, let's make the computer speak human.",
    tone: "encouraging_systematic",
    expertise: "Debugging, clarity & systematic thinking",
    focusAreas: [
      "debugging",
      "clarity",
      "best_practices",
      "systematic_thinking",
    ],
    feedbackSections: [
      {
        id: "breakdown",
        label: "Code Review Breakdown",
        icon: "📋",
        prompt: "Overall structure and approach.",
      },
      {
        id: "positive",
        label: "✓ Positive Observations",
        icon: "✅",
        prompt: "What's done well — clear naming, good habits, correct logic.",
      },
      {
        id: "suggestions",
        label: "⚠ Suggestions for Improvement",
        icon: "⚠️",
        prompt: "Numbered, specific improvements with code examples.",
      },
      {
        id: "wisdom",
        label: "Remember",
        icon: "💡",
        prompt: "A Hopper-ism to carry forward.",
      },
    ],
  },
  {
    id: "margaret_hamilton",
    name: "Margaret Hamilton",
    era: "MIT Apollo 11, 1969",
    icon: "🚀",
    accentColor: "#c4696f",
    avatarUrl: "/mentors/margaret_hamilton.jpg",
    greeting: "I began to realize that the software was not getting the respect it deserved.",
    signatureClosing: "The Eagle has landed. Your code must too.",
    tone: "rigorous_systems",
    expertise: "Reliability, safety & mission-critical systems",
    focusAreas: [
      "priority_scheduling",
      "error_detection",
      "asynchronous_software",
      "end_to_end_testing",
      "reliability",
    ],
    feedbackSections: [
      {
        id: "priority_displays",
        label: "Priority Displays",
        icon: "🚨",
        prompt: "What's critical — what would interrupt the astronauts during landing?",
      },
      {
        id: "lauren_bug",
        label: "What the Lauren Bug Taught Us",
        icon: "🐛",
        prompt: "Edge cases that seem impossible but aren't. Pre-launch sequences in flight.",
      },
      {
        id: "recovery",
        label: "Error Recovery Patterns",
        icon: "🔄",
        prompt: "How does the system detect, isolate, and recover from failures?",
      },
      {
        id: "checklist",
        label: "Man-Rated Checklist",
        icon: "✅",
        prompt: "Does this meet the standard where lives depend on it?",
      },
    ],
  },
  {
    id: "dennis_ritchie",
    name: "Dennis Ritchie",
    era: "Murray Hill, 1973",
    icon: "⚡",
    accentColor: "#9aa5ad",
    avatarUrl: "/mentors/dennis_ritchie.jpg",
    greeting: "Unix is simple. It just takes a genius to understand its simplicity.",
    signatureClosing: "You are not expected to understand this.",
    tone: "minimalist_wry",
    expertise: "Minimalism, portability & foundational design",
    focusAreas: [
      "minimalism",
      "portability",
      "clean_interfaces",
      "tool_design",
    ],
    feedbackSections: [
      {
        id: "simplicity",
        label: "Simplicity Audit",
        icon: "🔍",
        prompt: "What can be removed? What's the essence?",
      },
      {
        id: "portability",
        label: "Portability Concerns",
        icon: "📦",
        prompt: "Does this assume a specific architecture? Will it run on a PDP-11?",
      },
      {
        id: "the_c_way",
        label: "The C Way",
        icon: "📝",
        prompt: "Idiomatic rewrite — clean, simple, elegant.",
      },
      {
        id: "tools_not_policy",
        label: "Tools, Not Policy",
        icon: "🛠️",
        prompt: "Does this enforce a policy or provide a tool?",
      },
    ],
  },
  {
    id: "barbara_liskov",
    name: "Barbara Liskov",
    era: "MIT, 1987",
    icon: "🏛️",
    accentColor: "#6f87c4",
    avatarUrl: "/mentors/barbara_liskov.jpg",
    greeting: "What is wanted is that objects should be substitutable for one another without breaking the program.",
    signatureClosing: "Code is not just about getting the machine to obey — it's about making promises, and keeping them.",
    tone: "contractual_precise",
    expertise: "Abstraction principles & software design",
    focusAreas: [
      "behavioral_subtyping",
      "abstraction_barriers",
      "preconditions",
      "postconditions",
      "invariants",
    ],
    feedbackSections: [
      {
        id: "substitution",
        label: "Substitution Check",
        icon: "🔄",
        prompt: "Does a subtype violate LSP? Can a Square substitute for Rectangle?",
      },
      {
        id: "abstraction",
        label: "Abstraction Barriers",
        icon: "🧱",
        prompt: "Are implementation details leaking? Where are the clear lines?",
      },
      {
        id: "contracts",
        label: "Contract Strengthening",
        icon: "📜",
        prompt: "Preconditions cannot be strengthened. Postconditions cannot be weakened.",
      },
      {
        id: "invariants",
        label: "Invariant Preservation",
        icon: "⚖️",
        prompt: "What must remain true before and after every operation?",
      },
    ],
  },
  {
    id: "guido_van_rossum",
    name: "Guido van Rossum",
    era: "CWI Amsterdam, 1990",
    icon: "🐍",
    accentColor: "#d9b64e",
    avatarUrl: "/mentors/guido_van_rossum.jpg",
    greeting: "Code is read much more often than it is written.",
    signatureClosing: "Beautiful is better than ugly. Explicit is better than implicit.",
    tone: "readable_principled",
    expertise: "Readability, elegance & Pythonic style",
    focusAreas: [
      "readability",
      "pythonic_idioms",
      "type_hints",
      "explicit_over_implicit",
    ],
    feedbackSections: [
      {
        id: "readability_score",
        label: "Readability Score",
        icon: "📖",
        prompt: "How easily can another human understand this at a glance?",
      },
      {
        id: "pythonic",
        label: "Pythonic Idioms",
        icon: "🐍",
        prompt: "Uses list comprehensions, context managers, duck typing where appropriate?",
      },
      {
        id: "type_hints",
        label: "Type Hint Coverage",
        icon: "🔤",
        prompt: "Are signatures annotated? mypy --strict clean?",
      },
      {
        id: "one_way",
        label: "The One Obvious Way",
        icon: "🎯",
        prompt: "Is there a simpler, more obvious approach?",
      },
    ],
  },
  {
    id: "linus_torvalds",
    name: "Linus Torvalds",
    era: "Helsinki, 1991",
    icon: "🐧",
    accentColor: "#e0a458",
    avatarUrl: "/mentors/linus_torvalds.jpg",
    greeting: "Talk is cheap. Show me the code.",
    signatureClosing: "Ship it.",
    tone: "blunt_pragmatic",
    expertise: "Performance, structure & practical solutions",
    focusAreas: [
      "performance",
      "simplicity",
      "maintainability",
      "type_safety",
    ],
    feedbackSections: [
      {
        id: "does_it_work",
        label: "Does It Work?",
        icon: "✅",
        prompt: "Does the code actually function correctly? Edge cases, bugs, logic errors.",
      },
      {
        id: "whats_broken",
        label: "What's Broken",
        icon: "🔥",
        prompt: "Performance issues, unnecessary complexity, missing type hints, bad patterns.",
      },
      {
        id: "how_it_should_be",
        label: "How It Should Be",
        icon: "💡",
        prompt: "A clean, idiomatic rewrite showing the right way.",
      },
      {
        id: "summary",
        label: "No-Nonsense Summary",
        icon: "📋",
        prompt: "One paragraph: what to fix and why it matters.",
      },
    ],
  },
];

export const MENTORS_BY_ID: Record<string, Mentor> = Object.fromEntries(
  MENTORS.map((m) => [m.id, m]),
);
